"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ListPostsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___ListPostsRequest = ListPostsRequest

class ListPostsReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    POSTS_FIELD_NUMBER: builtins.int
    ERROR_MSG_FIELD_NUMBER: builtins.int
    @property
    def posts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PostDbEntry]: ...
    error_msg: typing.Text
    def __init__(self,
        *,
        posts: typing.Optional[typing.Iterable[global___PostDbEntry]] = ...,
        error_msg: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_msg",b"error_msg","posts",b"posts"]) -> None: ...
global___ListPostsReply = ListPostsReply

class SchedulePostReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ERROR_MSG_FIELD_NUMBER: builtins.int
    error_msg: typing.Text
    def __init__(self,
        *,
        error_msg: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_msg",b"error_msg"]) -> None: ...
global___SchedulePostReply = SchedulePostReply

class Post(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TEXT_POST_FIELD_NUMBER: builtins.int
    @property
    def text_post(self) -> global___TextPost: ...
    def __init__(self,
        *,
        text_post: typing.Optional[global___TextPost] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["post_type",b"post_type","text_post",b"text_post"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["post_type",b"post_type","text_post",b"text_post"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["post_type",b"post_type"]) -> typing.Optional[typing_extensions.Literal["text_post"]]: ...
global___Post = Post

class TextPost(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TITLE_FIELD_NUMBER: builtins.int
    SUBREDDIT_FIELD_NUMBER: builtins.int
    BODY_FIELD_NUMBER: builtins.int
    SCHEDULED_TIME_FIELD_NUMBER: builtins.int
    title: typing.Text
    subreddit: typing.Text
    body: typing.Text
    scheduled_time: builtins.int
    def __init__(self,
        *,
        title: typing.Text = ...,
        subreddit: typing.Text = ...,
        body: typing.Text = ...,
        scheduled_time: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["body",b"body","scheduled_time",b"scheduled_time","subreddit",b"subreddit","title",b"title"]) -> None: ...
global___TextPost = TextPost

class PostDbEntry(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ID_FIELD_NUMBER: builtins.int
    POSTED_FIELD_NUMBER: builtins.int
    POST_FIELD_NUMBER: builtins.int
    id: builtins.int
    posted: builtins.bool
    @property
    def post(self) -> global___Post: ...
    def __init__(self,
        *,
        id: builtins.int = ...,
        posted: builtins.bool = ...,
        post: typing.Optional[global___Post] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["post",b"post"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","post",b"post","posted",b"posted"]) -> None: ...
global___PostDbEntry = PostDbEntry

class EditPostRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class _Operation:
        ValueType = typing.NewType('ValueType', builtins.int)
        V: typing_extensions.TypeAlias = ValueType
    class _OperationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[EditPostRequest._Operation.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DELETE: EditPostRequest._Operation.ValueType  # 0
    class Operation(_Operation, metaclass=_OperationEnumTypeWrapper):
        """TODO support more operations if users request.
        For now we assume that if you want to edit its easier to just
        delete and start over again
        """
        pass

    DELETE: EditPostRequest.Operation.ValueType  # 0

    OPERATION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    operation: global___EditPostRequest.Operation.ValueType
    id: builtins.int
    def __init__(self,
        *,
        operation: global___EditPostRequest.Operation.ValueType = ...,
        id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["id",b"id","operation",b"operation"]) -> None: ...
global___EditPostRequest = EditPostRequest

class EditPostReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ERROR_MSG_FIELD_NUMBER: builtins.int
    error_msg: typing.Text
    def __init__(self,
        *,
        error_msg: typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["error_msg",b"error_msg"]) -> None: ...
global___EditPostReply = EditPostReply
